# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T01:02:13+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class JobType(Enum):
    JOB_TYPE_UNSPECIFIED = 'JOB_TYPE_UNSPECIFIED'
    PIPELINE = 'PIPELINE'
    QUERY = 'QUERY'
    ML_EXTERNAL = 'ML_EXTERNAL'


class State(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    PENDING = 'PENDING'
    ACTIVE = 'ACTIVE'


class Assignment(BaseModel):
    assignee: Optional[str] = Field(
        None,
        description='The resource which will use the reservation. E.g. `projects/myproject`, `folders/123`, or `organizations/456`.',
    )
    jobType: Optional[JobType] = Field(
        None, description='Which type of jobs will use the reservation.'
    )
    name: Optional[str] = Field(
        None,
        description='Output only. Name of the resource. E.g.: `projects/myproject/locations/US/reservations/team1-prod/assignments/123`. The assignment_id must only contain lower case alphanumeric characters or dashes and the max length is 64 characters.',
    )
    state: Optional[State] = Field(
        None, description='Output only. State of the assignment.'
    )


class Plan(Enum):
    COMMITMENT_PLAN_UNSPECIFIED = 'COMMITMENT_PLAN_UNSPECIFIED'
    FLEX = 'FLEX'
    TRIAL = 'TRIAL'
    MONTHLY = 'MONTHLY'
    ANNUAL = 'ANNUAL'


class RenewalPlan(Enum):
    COMMITMENT_PLAN_UNSPECIFIED = 'COMMITMENT_PLAN_UNSPECIFIED'
    FLEX = 'FLEX'
    TRIAL = 'TRIAL'
    MONTHLY = 'MONTHLY'
    ANNUAL = 'ANNUAL'


class State1(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    PENDING = 'PENDING'
    ACTIVE = 'ACTIVE'
    FAILED = 'FAILED'


class Empty(BaseModel):
    pass


class ListAssignmentsResponse(BaseModel):
    assignments: Optional[List[Assignment]] = Field(
        None, description='List of assignments visible to the user.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='Token to retrieve the next page of results, or empty if there are no more results in the list.',
    )


class MergeCapacityCommitmentsRequest(BaseModel):
    capacityCommitmentIds: Optional[List[str]] = Field(
        None,
        description="Ids of capacity commitments to merge. These capacity commitments must exist under admin project and location specified in the parent. ID is the last portion of capacity commitment name e.g., 'abc' for projects/myproject/locations/US/capacityCommitments/abc",
    )


class MoveAssignmentRequest(BaseModel):
    destinationId: Optional[str] = Field(
        None,
        description='The new reservation ID, e.g.: `projects/myotherproject/locations/US/reservations/team2-prod`',
    )


class Reservation(BaseModel):
    concurrency: Optional[str] = Field(
        None,
        description='Job concurrency target which sets a soft upper bound on the number of jobs that can run concurrently in this reservation. This is a soft target due to asynchronous nature of the system and various optimizations for small queries. Default value is 0 which means that concurrency target will be automatically computed by the system. NOTE: this field is exposed as `target_job_concurrency` in the Information Schema, DDL and BQ CLI.',
    )
    creationTime: Optional[str] = Field(
        None, description='Output only. Creation time of the reservation.'
    )
    ignoreIdleSlots: Optional[bool] = Field(
        None,
        description='If false, any query or pipeline job using this reservation will use idle slots from other reservations within the same admin project. If true, a query or pipeline job using this reservation will execute with the slot capacity specified in the slot_capacity field at most.',
    )
    multiRegionAuxiliary: Optional[bool] = Field(
        None,
        description="Applicable only for reservations located within one of the BigQuery multi-regions (US or EU). If set to true, this reservation is placed in the organization's secondary region which is designated for disaster recovery purposes. If false, this reservation is placed in the organization's default region.",
    )
    name: Optional[str] = Field(
        None,
        description='The resource name of the reservation, e.g., `projects/*/locations/*/reservations/team1-prod`. The reservation_id must only contain lower case alphanumeric characters or dashes. It must start with a letter and must not end with a dash. Its maximum length is 64 characters.',
    )
    slotCapacity: Optional[str] = Field(
        None,
        description="Minimum slots available to this reservation. A slot is a unit of computational power in BigQuery, and serves as the unit of parallelism. Queries using this reservation might use more slots during runtime if ignore_idle_slots is set to false. If the new reservation's slot capacity exceeds the project's slot capacity or if total slot capacity of the new reservation and its siblings exceeds the project's slot capacity, the request will fail with `google.rpc.Code.RESOURCE_EXHAUSTED`. NOTE: for reservations in US or EU multi-regions, slot capacity constraints are checked separately for default and auxiliary regions. See multi_region_auxiliary flag for more details.",
    )
    updateTime: Optional[str] = Field(
        None, description='Output only. Last update time of the reservation.'
    )


class SearchAssignmentsResponse(BaseModel):
    assignments: Optional[List[Assignment]] = Field(
        None, description='List of assignments visible to the user.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='Token to retrieve the next page of results, or empty if there are no more results in the list.',
    )


class SplitCapacityCommitmentRequest(BaseModel):
    slotCount: Optional[str] = Field(
        None, description='Number of slots in the capacity commitment after the split.'
    )


class Status(BaseModel):
    code: Optional[int] = Field(
        None,
        description='The status code, which should be an enum value of google.rpc.Code.',
    )
    details: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='A list of messages that carry the error details. There is a common set of message types for APIs to use.',
    )
    message: Optional[str] = Field(
        None,
        description='A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.',
    )


class TableReference(BaseModel):
    datasetId: Optional[str] = Field(
        None, description='The ID of the dataset in the above project.'
    )
    projectId: Optional[str] = Field(
        None, description='The assigned project ID of the project.'
    )
    tableId: Optional[str] = Field(
        None, description='The ID of the table in the above dataset.'
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class BiReservation(BaseModel):
    name: Optional[str] = Field(
        None,
        description='The resource name of the singleton BI reservation. Reservation names have the form `projects/{project_id}/locations/{location_id}/biReservation`.',
    )
    preferredTables: Optional[List[TableReference]] = Field(
        None, description='Preferred tables to use BI capacity for.'
    )
    size: Optional[str] = Field(None, description='Size of a reservation, in bytes.')
    updateTime: Optional[str] = Field(
        None, description='Output only. The last update timestamp of a reservation.'
    )


class CapacityCommitment(BaseModel):
    commitmentEndTime: Optional[str] = Field(
        None,
        description='Output only. The end of the current commitment period. It is applicable only for ACTIVE capacity commitments.',
    )
    commitmentStartTime: Optional[str] = Field(
        None,
        description='Output only. The start of the current commitment period. It is applicable only for ACTIVE capacity commitments.',
    )
    failureStatus: Optional[Status] = Field(
        None,
        description='Output only. For FAILED commitment plan, provides the reason of failure.',
    )
    multiRegionAuxiliary: Optional[bool] = Field(
        None,
        description="Applicable only for commitments located within one of the BigQuery multi-regions (US or EU). If set to true, this commitment is placed in the organization's secondary region which is designated for disaster recovery purposes. If false, this commitment is placed in the organization's default region.",
    )
    name: Optional[str] = Field(
        None,
        description='Output only. The resource name of the capacity commitment, e.g., `projects/myproject/locations/US/capacityCommitments/123` The commitment_id must only contain lower case alphanumeric characters or dashes. It must start with a letter and must not end with a dash. Its maximum length is 64 characters.',
    )
    plan: Optional[Plan] = Field(
        None, description='Capacity commitment commitment plan.'
    )
    renewalPlan: Optional[RenewalPlan] = Field(
        None,
        description='The plan this capacity commitment is converted to after commitment_end_time passes. Once the plan is changed, committed period is extended according to commitment plan. Only applicable for ANNUAL commitments.',
    )
    slotCount: Optional[str] = Field(
        None, description='Number of slots in this commitment.'
    )
    state: Optional[State1] = Field(
        None, description='Output only. State of the commitment.'
    )


class ListCapacityCommitmentsResponse(BaseModel):
    capacityCommitments: Optional[List[CapacityCommitment]] = Field(
        None, description='List of capacity commitments visible to the user.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='Token to retrieve the next page of results, or empty if there are no more results in the list.',
    )


class ListReservationsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='Token to retrieve the next page of results, or empty if there are no more results in the list.',
    )
    reservations: Optional[List[Reservation]] = Field(
        None, description='List of reservations visible to the user.'
    )


class SplitCapacityCommitmentResponse(BaseModel):
    first: Optional[CapacityCommitment] = Field(
        None, description='First capacity commitment, result of a split.'
    )
    second: Optional[CapacityCommitment] = Field(
        None, description='Second capacity commitment, result of a split.'
    )
